version: '3.8'

services:
  # K-Means Trading Strategy Server
  kmeans-trading:
    build: .
    container_name: kmeans-trading-server
    ports:
      - "8765:8765"  # WebSocket server port
    environment:
      # Override configuration with environment variables
      - KMEANS_WS_HOST=0.0.0.0
      - KMEANS_WS_PORT=8765
      - KMEANS_LOG_LEVEL=INFO
      # Interactive Brokers connection (uncomment and modify as needed)
      # - KMEANS_IB_HOST=host.docker.internal  # For connecting to TWS on host machine
      # - KMEANS_IB_PORT=7497
    volumes:
      # Mount configuration file (optional, for easy config changes)
      - ./config.yaml:/app/config.yaml:ro
      # Mount logs directory (optional)
      - ./logs:/app/logs
    networks:
      - kmeans-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import websockets; import asyncio; asyncio.run(websockets.connect('ws://localhost:8765'))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Web Dashboard (Nginx serving static files)
  dashboard:
    image: nginx:alpine
    container_name: kmeans-dashboard
    ports:
      - "8080:80"  # Web dashboard port
    volumes:
      - ./src/dashboard.html:/usr/share/nginx/html/index.html:ro
      - ./src/dashboard.js:/usr/share/nginx/html/dashboard.js:ro
      - ./src/dashboard.css:/usr/share/nginx/html/dashboard.css:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - kmeans-network
    depends_on:
      - kmeans-trading
    restart: unless-stopped

networks:
  kmeans-network:
    driver: bridge

# Optional: Add volumes for persistent data
volumes:
  logs:
    driver: local